name: test

on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  test-and-build:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.19
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Use Cache
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Get dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        go mod download
    - name: Upload coverage report
      uses: codecov/codecov-action@v2
      with:
        files: ./coverprofile.out
        fail_ci_if_error: true
        verbose: true
      if: ${{ steps.unittest.conclusion == 'success' || steps.unittest.conclusion == 'failure' }}
    - name: Build
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: build --snapshot --rm-dist
